language: php
php:
  - 5.4
  - 5.5

env:
  - CONTAO_VERSION="3.5.*"

sudo: false

install:
    - mysql -e 'CREATE DATABASE isotope_core_testsuite;'
    - sed '$d' composer.json | sed '$d' > composer.new
    - 'echo ''},"prefer-stable": true,"minimum-stability": "dev"}'' >> composer.new'
    - mv composer.new composer.json
    - composer update
    - composer create-project -s dev contao/core:${CONTAO_VERSION} contao
    - cp -R system/modules/isotope contao/system/modules/isotope
    - cp -R system/modules/isotope_reports contao/system/modules/isotope_reports
    - cp -R system/modules/isotope_rules contao/system/modules/isotope_rules
    - cp -R vendor/terminal42/contao-conditionalselectmenu contao/system/modules/conditionalselectmenu
    - cp -R vendor/terminal42/contao-namespace-class-loader contao/system/modules/_autoload
    - cp -R vendor/terminal42/dcawizard contao/system/modules/dcawizard
    - cp -R vendor/codefog/contao-haste contao/system/modules/haste
    - cp -R vendor/menatwork/contao-multicolumnwizard contao/system/modules/multicolumnwizard
    - cp -R vendor/terminal42/contao-tablelookupwizard contao/system/modules/tablelookupwizard
    - cp -R vendor/terminal42/notification_center contao/system/modules/notification_center
    - cd contao/system/modules/isotope
    - cp test/fixtures/travis/initconfig.php ../../config/initconfig.php
    - cp test/fixtures/travis/langconfig.php ../../config/langconfig.php
    - cp test/fixtures/travis/localconfig.php ../../config/localconfig.php
    - cp test/fixtures/travis/pathconfig.php ../../config/pathconfig.php

script: phpunit --configuration test/phpunit.xml --bootstrap test/bootstrap.php ./test
